### ISSUE TITLE
Stange error

### ISSUE THREAD

**Issue by 3ezzdin99** [peterm790/weather_routing#1]
while building the conda env a strange error shows up

**Comment by 3ezzdin99** [comment]
It gets too much time loading till the system shuts it down. I tried it on many pcs and the same error shows up

**Comment by peterm790** [comment]
HI @3ezzdin99, that's strange there are fairly few dependencies in the recommended environment so it should be a fairly quick install. I'm not able to replicate the problem on my side. You could try setting up a clean environment and installing the dependencies listed in `environment.yml` one at a time or try installing them using pip rather than conda. 

Another option is to consider using [Mamba](https://mamba.readthedocs.io/en/latest/) which is a drop in replacement for conda and tends to be a lot faster, but this really shouldn't be necessary for your needs.
